<?php 
include APP_PATH . 'view' . DIRECTORY_SEPARATOR . 'admin'. DIRECTORY_SEPARATOR .'adminTemplate.phtml';
?>
<div class="col-md-9">   
<a class="btn btn-primary btn-lg btn-block" href="<?php App::config('url'); ?>AdminUsers/createUsers ">Create new user</a>
<br>
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Name</th>
                <th scope="col">Lastname</th>
                <th scope="col">Role</th>
                <th scope="col">Email</th>
                <th scope="col">Set user</th>  
                <th scope="col">Set admin</th>
                <th scope="col">Update</th>  
                <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                <?php if(isset($users)): ?>
                <?php foreach ($users as $key): ?>
                <tr>
                <td><?php echo $key-> name ?></td>
                <td><?php echo $key-> lastname ?></td>
                <td><?php echo $key-> role ?></td>
                <td><?php echo $key-> email ?></td>
                <td><a style="color:red" href="<?= App::config('url');?>AdminUsers/setUser/<?= $key->id ?>"><i title="set user" class="fas fa-2x fa-user-lock"></i></a></td>
                <td><a style="color:green" href="<?= App::config('url');?>AdminUsers/setAdmin/<?= $key->id ?>"><i title="Set admin" class="fas fa-2x fa-user-edit"></i></a></td>
                <td><a href="<?= App::config('url');?>AdminUsers/updateUsers/<?= $key->id ?>"><i title="update" class="fas fa-2x fa-pencil-alt"></i></a></td>
                <td><a style="color:red" href="<?= App::config('url');?>AdminUsers/deleteUsers/<?= $key->id ?>"><i title="detele" class="fas fa-2x fa-trash-alt"></i></a></td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="<?= App::config('url').$pagination['path']. '1' ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
                </a>
            </li>
            <?php 

            for ($i=$pagination['page']-2; $i <= $pagination['maxPage']; $i++): ?>
                <?php if($i > 0 && $i <= $pagination['itemsNumber']): ?>
                    <?php if($pagination['page'] == $i): ?>
                    <li class='page-item active'><a class='page-link' href='<?= App::config('url').$pagination['path']. $i ?>'><?= $i ?></a></li>
                    <?php else:?>
                    <li class='page-item'><a class='page-link' href='<?= App::config('url').$pagination['path']. $i ?>'><?= $i ?></a></li>
                    <?php endif ?> 
                <?php endif ?>
            <?php endfor ?>

            <li class="page-item">
                <a class="page-link" href="<?= App::config('url').$pagination['path']. $pagination['itemsNumber'] ?>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
                </a>
            </li>
            </ul>
        </nav>
        <hr>
        <form action="<?= App::config('url'); ?>AdminUsers" method="post">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <input type="text" name="email" class="form-control" placeholder="Search users by email">
                    <br>
                    <?php if(isset($error)): ?>
                        <h5 style = "color:red"><?= $error ?></h5>
                    <?php endif ?>
                    </div>
                    <div class="col-sm">
                        <input type="submit" name="submit" class="btn btn-primary" value="Search">  
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>
</div>