<div class="container padding-bottom-3x mb-1">
    <!-- Shopping Cart-->
    <div class="table-responsive shopping-cart">
        <table class="table">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th class="text-center">Subtotal</th>
                    <th class="text-center">Discount</th>
                    <th class="text-center"><a class="btn btn-sm btn-outline-danger" href="<?= App::config('url');?>Cart/destroyCart">Clear Cart</a></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_SESSION['Cart'] as $key):?>
                    <td>
                        <div class="product-item">
                            <a class="product-thumb" href="#"><img src="<?= App::config('url');?>/public/images/<?=$key['image']?>" alt="Product"></a>
                            <div class="product-info">
                                <h4 class="product-title"><a href="<?= App::config('url');?>index/productpage/<?=$key['id']?>"><?= $key['title'] ?></a></h4><span><em>Author:</em> <?= $key['author'] ?></span>
                            </div>
                        </div>
                    </td>
                    <td class="text-center text-lg text-medium">$<?= $key['price'] * $key['quantityInCart']?></td>
                    <td class="text-center"><?= $key['discount'] ?></td>
                    <td class="text-center"><a class="remove-from-cart" href="<?= App::config('url');?>Cart/removeProduct/<?=$key['id']?>" data-toggle="tooltip" title="" data-original-title="Remove item"><i class="fas fa-2x fa-trash-alt"></i></a></td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="shopping-cart-footer">
        <div class="column">
            <div class="coupon-form">
                <input class="form-control form-control-sm" type="text" placeholder="Coupon code" required="">
                <button class="btn btn-outline-primary btn-sm" type="submit">Apply Coupon</button>
            </div>
        </div>
        <div class="column text-lg">Subtotal: <span class="text-medium"><?= producthelper::totalprice(); ?></span></div>
    </div>
    <div class="shopping-cart-footer">
        <div class="column"><a class="btn btn-outline-secondary" href="<?= App::config('url'); ?>"><i class="icon-arrow-left"></i>&nbsp;Back to Shopping</a></div>
        <div class="column"><a class="btn btn-success" href="#">Checkout</a></div>
    </div>
</div>
