<?php if(!isset($_SERVER['REDIRECT_PATH_INFO'])): ?>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
  <?php for ($i=0; $i < count($visible) ; $i++):?>
    <li data-target="#carouselExampleIndicators" data-slide-to="<?=$i ?>" class="<?php if($i == 0) echo 'active'?>"></li>
    <?php endfor?>
  </ol>
  <div class="carousel-inner">
  <?php for ($i=0; $i < count($visible) ; $i++):?>
    <div class="carousel-item <?php if($i == 0) echo 'active'; ?>">
      <img class="d-block w-100" src="../../public/images/<?= $visible[$i]->photo?>">
    </div>
    <?php endfor?>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<?php endif ?>
<hr><br>
<div class="container">
   <div class="row">
       <div class="col-md-3">  
       <div id="list-example" class="list-group">
        <h3 class="text-center">Categories</h3>
            <hr>
            <a class="list-group-item list-group-item-action" href="<?= App::config('url')?>">See all</a>
            <?php foreach($categories as $category): ?>
            <a class="list-group-item list-group-item-action" href="<?= App::config('url'); ?>index/index/<?= $category->id ?>"><?= $category->name; ?>(<?= $ProductsInCategory[$category->name] ?>)</a>
            <?php endforeach;?>
        </div>
       </div>
       <div class="col-md-9">
        <h2 class="text-center"><?= $bigTitle ?></h2>
        <?php if(isset($displayCategory)):?>
          <hr>
          <h3 class="text-center"><?=$displayCategory ?></h3>

        <?php endif ?>
        <hr>
            <div class="container">
                <div class="row">
                    <?php foreach($products as $product): ?>
                        
                    <div class="col-md-4 mt-5">  
                        <div class="card" style="width: 14rem;">
                            <img style ="max-height:200px" class="card-img-top" src="../../public/images/<?= $product->image ?>" alt="Card image cap">
                            <div class="card-body">
                                <a href="<?=App::config('url')?>index/productpage/<?= $product->id ?>"><h4 class="card-title text-center"><?= $product->title?></h4></a>
                                <p class="card-text text-center"><?php Request::LimitString($product->content,95) ?></p>
                                <p class="card-text text-center"> Author: <?= $product->author ?></p>
                                <h5 class="card-text text-center"> Price: <?= $product->price ?>$</h5>
                                <p class="card-text text-center"> Rating: <?=Util::stars($product->rating,'')?></p>
                            </div>
                            <a href="<?=App::config('url')?>index/productpage/<?= $product->id ?>" class="btn btn-primary btn-lg btn-block">Buy</a>
                        </div>
                    </div>

                    <?php endforeach;?>
                </div>
                <br>
                <?=Util::Pagination($pagination)?>
            </div>
       </div>
    </div>
</div>
