<br><br>
<div class="container">
  <div class="row">
      <div class="col-md-6 col-sm-12">
        <img class="img-thumbnail" src="../../public/images/<?= $product -> image ?>">
      </div>
      <div class="col-md-6 text-center ">
        <h2 class = "text-center"><?= $product -> title ?></h2><hr> 
        
        <h4>Price</h4>
        <p><?= $product -> price ?>$</p>
        <h4>Status</h4>
        <p><?= $availability ?></p>
        <h4>Rating</h4>
        <p><?= $availability ?></p>
        <a href="#" class="btn btn-primary btn-lg btn-block">Buy</a>
    </div>
  </div><br><br>
  <h2 class="text-center">About product</h2>
  <p class="text-center border"><?=  $product -> content?></p>
    <br>
  <div class="container bootstrap snippets bootdey">
    <div class="row">
		<div class="col-md-12">
		    <div class="blog-comment">
				<h2 class="text-center">Comments</h2>
                <hr/>
				<ul class="comments">
        <?php foreach($comments as $key) :?>
				<li class="clearfix">
				  <div class="post-comments">
				      <p class="meta"><?= $key->comment_date ?> <b><?= $key->name ?></b> says : <i class="pull-right"></i></p>
				      <p>
              <?= $key->comment ?>
				      </p>
				  </div>
				</li>
        <?php endforeach ?>
        <?=Util::Pagination($pagination)?>
        <br>
        
        <li class="clearfix">
            <div class="post-comments">
                <form action="<?=App::config('url')?>index/productpage/<?= $product->id ?>" method="POST">
                    <div class="form-group">
                        <input type="text" class="form-control" name="content">
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Submit">
                    </div>
                    <?php if(isset($commentError)): ?>
                      <h5 style='color:red'><?= $commentError?></h5>
                    <?php endif ?>
                </form>
            </div>
        </li>
				</ul>
			</div>
		</div>
	</div>
</div>