<?php 
include APP_PATH . 'view' . DIRECTORY_SEPARATOR . 'admin'. DIRECTORY_SEPARATOR .'adminTemplate.phtml';
?>
<div class="col-md-9">   
<a class="btn btn-primary btn-lg btn-block" href="<?php App::config('url');?>AdminSlideshow/addPhoto">Add photo</a>
    <div class="container">
        <br>
        <h2 class="text-center">Choice image</h2>
        <hr>
        <div class="row">
            <?php foreach($photos as $key):?>
            <div class="col-sm mt-5">
                <div class="card" style="width: 14rem;">
                <a class="btn btn-danger btn-lg" href="<?php App::config('url');?>AdminSlideshow/deletePhoto/<?=$key->id?>">DELETE</a>
                <a href="<?= App::config('url')?>AdminSlideshow/setPhoto/<?=$key->id?>">
                <img class=" <?php if($key->visible == 1){ echo 'borderimg'; }else{ echo 'removebox-sizing'; } ?>" style ="max-width:200px" src="../../public/images/<?=$key->photo?>">
            </a>
            </div>
            </div>
            <?php endforeach?>
        </div>
    </div>
    <br><br>
    <h2 class="text-center">Visible images</h2>
    <hr>
    <div class="row">
            <?php foreach($visiblePhotos as $key):?>
            <div class="col-sm mt-5">
                <div class="card" style="width: 14rem;">
                <a href="<?= App::config('url')?>AdminSlideshow/setPhoto/<?=$key->id?>">
                <img class="removebox-sizing" style ="max-width:200px" src="../../public/images/<?=$key->photo?>">
            </a>
            </div>
            </div>
            <?php endforeach?>
        </div>

        
</div>
</div>
</div>