<?php 
include APP_PATH . 'view' . DIRECTORY_SEPARATOR . 'admin'. DIRECTORY_SEPARATOR .'adminTemplate.phtml';
?>
<div class="col-md-9">   
<a class="btn btn-primary btn-lg btn-block" href="<?php App::config('url');?>AdminProducts/createProducts ">Create new product</a>
<br>
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Image</th>
                <th scope="col">Price</th>  
                <th scope="col">Category</th>
                <th scope="col">Quantity</th>  
                <th scope="col">Content</th>
                <th scope="col">Pdf</th> 
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                <?php if(isset($products)): ?>
                <?php foreach ($products as $key): ?>
                <tr>
                <td><?= $key-> title ?></td>
                <td><?= $key-> author ?></td>
                <td><img style ="max-width:80px" src="public/images/<?=$key->image ?>"></td>
                <td><?= $key-> price ?></td>
                <td><?= $key-> category ?></td>
                <td><?= $key-> quantity ?></td>
                <td>
                    <?php 
                    Request::LimitString($key->content, 10);
                    ?>
                </td>
                <td><?= $key-> pdf ?></td>
                <td><a href="<?= App::config('url');?>AdminProducts/updateProducts/<?= $key->id ?>"><i title="update" class="fas fa-2x fa-pencil-alt"></i></a></td>
                <td><a style="color:red" href="<?= App::config('url');?>AdminProducts/deleteProducts/<?= $key->id ?>"><i title="detele" class="fas fa-2x fa-trash-alt"></i></a></td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
            <li class="page-item">
                <a class="page-link" href="<?= App::config('url').$pagination['path']. '1' ?>" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
                </a>
            </li>
            <?php 

            for ($i=$pagination['page']-2; $i <= $pagination['maxPage']; $i++): ?>
                <?php if($i > 0 && $i <= $pagination['itemsNumber']): ?>
                    <?php if($pagination['page'] == $i): ?>
                    <li class='page-item active'><a class='page-link' href='<?= App::config('url').$pagination['path']. $i ?>'><?= $i ?></a></li>
                    <?php else:?>
                    <li class='page-item'><a class='page-link' href='<?= App::config('url').$pagination['path']. $i ?>'><?= $i ?></a></li>
                    <?php endif ?> 
                <?php endif ?>
            <?php endfor ?>

            <li class="page-item">
                <a class="page-link" href="<?= App::config('url').$pagination['path']. $pagination['itemsNumber'] ?>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
                </a>
            </li>
            </ul>
        </nav>
        <hr>
        <form action="<?= App::config('url'); ?>AdminProducts" method="post">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <input type="text" name="title" class="form-control" placeholder="Search products by title">
                    <br>
                    <?php if(isset($error)): ?>
                        <h5 style = "color:red"><?= $error ?></h5>
                    <?php endif ?>
                    </div>
                    <div class="col-sm">
                        <input type="submit" name="submit" class="btn btn-primary" value="Search">  
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>
</div>