<?php 
include APP_PATH . 'view' . DIRECTORY_SEPARATOR . 'admin'. DIRECTORY_SEPARATOR .'adminTemplate.phtml';
?>
<div class="col-md-9">   
<a class="btn btn-primary btn-lg btn-block" href="<?php App::config('url');?>AdminProducts/createProducts ">Create new product</a>
<br>
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Image</th>
                <th scope="col">Price</th>  
                <th scope="col">Category</th>
                <th scope="col">Quantity</th>  
                <th scope="col">Content</th>
                <th scope="col">Pdf</th> 
                <th scope="col">Update</th>
                <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                <?php if(isset($products)): ?>
                <?php foreach ($products as $key): ?>
                <tr>
                <td><?= $key-> title ?></td>
                <td><?= $key-> author ?></td>
                <td><img style ="max-width:80px" src="public/images/<?=$key->image ?>"></td>
                <td><?= $key-> price ?></td>
                <td><?= $key-> category ?></td>
                <td><?= $key-> quantity ?></td>
                <td><?= $key-> content ?></td>
                <td><?= $key-> pdf ?></td>
                <td><a href="<?= App::config('url');?>AdminProducts/updateProducts/<?= $key->id ?>"><i title="update" class="fas fa-2x fa-pencil-alt"></i></a></td>
                <td><a style="color:red" href="<?= App::config('url');?>AdminProducts/deleteProducts/<?= $key->id ?>"><i title="detele" class="fas fa-2x fa-trash-alt"></i></a></td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
        <hr>
        <form action="<?= App::config('url'); ?>AdminProducts" method="post">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <input type="text" name="email" class="form-control" placeholder="Search products by title">
                    <br>
                    <?php if(isset($error)): ?>
                        <h5 style = "color:red"><?= $error ?></h5>
                    <?php endif ?>
                    </div>
                    <div class="col-sm">
                        <input type="submit" name="submit" class="btn btn-primary" value="Search">  
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>
</div>