<?php include_once 'adminTemplate.phtml'?>
<div class="col-md-9"> 
<a class="btn btn-danger" href="<?= App::config('url');?>Admin/users">Back</a>
<br><br>
        <form action="<?= App::config('url'); ?>Admin/createUsers" method="post">
            <div class="form-group">
                <h4>Create user</h4>
                <hr>
                <div class="mb-3">
                    <div class="row">
                        <div class="col">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" name="name" class="form-control" id="name" value = "<?= $returnField['name'] ?>" placeholder="Enter user name">
                        <h5 style="color:red"><?= $errors['name']?></h5>
                        </div>
                        <div class="col">
                        <label for="lastname"  class="form-label">Lastname</label>
                        <input type="text" name="lastname" class="form-control" id="lastname" value = "<?= $returnField['lastname'] ?>" placeholder="Enter user lastname">
                        <h5 style="color:red"><?= $errors['lastname']?></h5>
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" class="form-control" id="email" value = "<?= $returnField['email'] ?>" placeholder="Your user email">
                    <h5 style="color:red"><?= $errors['email']?></h5>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="password" value = "<?= $returnField['password'] ?>" placeholder="Set user password">
                    <h5 style="color:red"><?= $errors['password']?></h5>
                </div>
                <div class="mb-3">
                    <label for="confirmPassword" class="form-label">Confirm password</label>
                    <input type="password" name="confirmPassword" class="form-control" id="confirmPassword" value = "<?= $returnField['confirmPassword'] ?>" placeholder="Confirm password">
                </div>
                <input type="submit" name="submit" class="btn btn-primary" value="Add">
                <h5 style="color:green"><?= $succesMsg?></h5>
                <br><br>
            </div>
        </form>
    </div>
    </div>
</div>