<?php include_once 'adminTemplate.phtml'?>

    <div class="col-md-9">  
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Name</th>
                <th scope="col">#</th>  
                <th scope="col">#</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
                </tr>
            </tbody>
        </table>
    </div>
    </div>
</div>