<br><br>
<div class="container">
   <div class="row">
       <div class="col-md-3">  
       <div id="list-example" class="list-group">
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>AdminStatistics">Statistics</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>AdminCategories">Categories</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>AdminUsers">Users</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>AdminProducts">Products</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>AdminOrders">Orders</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>AdminComments">Comments</a>
        </div>
    </div>
