<?php include_once 'adminTemplate.phtml'?>
<div class="col-md-9"> 
<a class="btn btn-danger" href="<?= App::config('url');?>AdminProducts">Back</a>
<br><br>
        <form action="<?= App::config('url'); ?>AdminProducts/updateProducts<?= $returnField['id'] ?> " method="post" enctype="multipart/form-data">
            <div class="form-group">
                <h4>Update product</h4>
                <hr>
                <div class="mb-3">
                    <div class="row">
                        <div class="col">
                        <label for="title" class="form-label">Title</label>
                        <input type="text" name="title" class="form-control" id="title" value = "<?= $returnField['title'] ?>">
                        </div>
                        <div class="col">
                        <label for="author"  class="form-label">Author</label>
                        <input type="text" name="author" class="form-control" id="author" value = "<?= $returnField['author'] ?>">
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                <label for="image" class="form-label">Image</label><br>
                    <input type="file" name="image" id="image">
                </div>
                <div class="mb-3">
                    <label for="price" class="form-label">Price</label>
                    <input type="text" name="price" class="form-control" id="price" value = "<?= $returnField['price'] ?>">
                </div>
                <div class="mb-3">
                    <label for="category" class="form-label">Category</label>
                    <input type="text" name="category" class="form-control" id="category" value = "<?= $returnField['category'] ?>">
                </div>
                <div class="mb-3">
                    <label for="quantity" class="form-label">Quantity</label>
                    <input type="text" name="quantity" class="form-control" id="quantity" value = "<?= $returnField['quantity'] ?>">
                </div>
                <div class="mb-3">
                    <label for="pdf" class="form-label">Pdf</label>
                    <input type="text" name="pdf" class="form-control" id="pdf" value = "<?= $returnField['pdf'] ?>">
                </div>
                <div class="mb-3">
                    <label for="w3review">Content:</label>
                    <br>
                    <textarea class="form-control" id="content" name="content" rows="4" cols="50"><?= $returnField['content'] ?></textarea>
                </div>
                <input type="submit" name="submit" class="btn btn-primary" value="Update">
                <br><br>
            </div>
        </form>
    </div>
    </div>
</div>