<br><br>
<div class="container">
   <div class="row">
       <div class="col-md-3">  
       <div id="list-example" class="list-group">
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>Admin">Statistics</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>Admin/categories">Categories</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>Admin/users">Users</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>Admin/products">Products</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>Admin/orders">Orders</a>
            <a class="list-group-item list-group-item-action" href="<?=App::config('url');?>Admin/comments">Comments</a>
        </div>
    </div>
