<?php include_once 'adminTemplate.phtml'?>
<div class="col-md-9"> 
<a class="btn btn-danger" href="<?= App::config('url');?>AdminUsers">Back</a>
<br><br>
        <form action="<?= App::config('url'); ?>AdminUsers/updateUsers/<?= $returnField['id']?>" method="post">
            <div class="form-group">
                <h4>Update user</h4>
                <hr>
                <div class="mb-3">
                    <div class="row">
                        <div class="col">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" name="name" class="form-control" id="name" value = "<?= $returnField['name'] ?>">
                        </div>
                        <div class="col">
                        <label for="lastname"  class="form-label">Lastname</label>
                        <input type="text" name="lastname" class="form-control" id="lastname" value = "<?= $returnField['lastname'] ?>">
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="role" class="form-label">Role</label>
                    <input type="role" name="role" class="form-control" id="role" value = "<?= $returnField['role'] ?>">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" class="form-control" id="email" value = "<?= $returnField['email'] ?>">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="password" value = "<?= $returnField['password'] ?>">
                </div>
                <input type="submit" name="submit" class="btn btn-primary" value="Update">
                <h5 style="color:green"><?= $succesMsg?></h5>
                <br><br>
            </div>
        </form>
    </div>
    </div>
</div>